### ISSUE TITLE
Please consider adding cross-compatibility with SlightlyFasterInteractables new ping icons. 

### ISSUE THREAD

**Issue by Nordblum** [artyredd/MiniMapMod#10]
It would look fantastic and make this mod much more useful. 
Here are some of the new icons added by [that mod](https://thunderstore.io/package/Wolfo/SlightlyFasterInteractables/). 
![image](https://user-images.githubusercontent.com/10522412/137622510-38e2f52d-b454-456f-a4b7-741640260e07.png)

**Comment by DekuDesu** [comment]
Added abstractions for SpriteManager.cs to allow developers to easily implement an ISpriteManager for mod compatibility that include sprites, see 2aa08aa
