### ISSUE TITLE
Icons aren't shown or located wrong after 3.3.1

### ISSUE THREAD

**Issue by xysztm** [artyredd/MiniMapMod#55]
I disable elevation markers. Sometimes I stay on the equipment barrel but no icon is shown while sometimes I rush to the shrine icon but find nothing from top to bottom.

**Comment by DekuDesu** [comment]
Could you provide me a copy of your configuration file please? I'm not able to reproduce this behavior.

**Comment by xysztm** [comment]
> Could you provide me a copy of your configuration file please? I'm not able to reproduce this behavior.

OK.
[MiniMap.zip](https://github.com/DekuDesu/MiniMapMod/files/8322513/MiniMap.zip)

**Comment by DekuDesu** [comment]
Are you still having this issue after HotFix 3.3.2?

**Comment by xysztm** [comment]
> Are you still having this issue after HotFix 3.3.2?

Yes. Sometimes the map is also very "large" or "small". I can only see icons when I stand very close with the chests with default zoom level. Or I can only see the player icon above a shrine icon wherever my player move. Maybe this is a bug with resolution? I choose 1080p with a 1440p monitor for FPS.

**Comment by artyredd** [comment]
Not reproducible
